name: focus_lock
description: FocusLock â€“ Android App to Block Instagram with Delayed Unlock & Physical Challenge
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_secure_storage: ^9.0.0
  device_info_plus: ^10.0.0
  permission_handler: ^11.4.3
  pedometer: ^3.1.3
  intl: ^0.19.0
  provider: ^6.0.0
  shared_preferences: ^2.2.0
  http: ^1.1.0
  encrypt: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
